apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  # metadata is used to match the target to patch
  name: chaintrap-maptool
spec:
  serviceAccountName: chaintrap
  images:
  - name: chaintrap-maptool
    newName: eu.gcr.io/hoy-dev-1/chaintrap-maptool
    newTag: main-24 # {"$imagepolicy": "chaintrap:chaintrap-maptool-main:tag"}
