apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "chaintrap-hoy-polysensus-io"
spec:
  commonName: "chaintrap.hoy.polysensus.io"
  secretName: chaintrap-hoy-polysensus-io
  dnsNames:
    - "chaintrap.hoy.polysensus.io"
    - "*.chaintrap.hoy.polysensus.io"
  issuerRef:
    name: letsencrypt-staging-primary-dns
    kind: ClusterIssuer
