---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: chaintrap-maptool
spec:
  interval: 2m
  # url: https://github.com/polysensus/chaintrap-maptool
  ref:
    branch: main
  url: ssh://git@github.com/polysensus/chaintrap-maptool.git
  secretRef:
    name: chaintrap-maptool

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: chaintrap-maptool
spec:
  interval: 2m
  path: ./k8s/chaintrap-maptool
  prune: true
  sourceRef:
    kind: GitRepository
    name: chaintrap-maptool
